#!/usr/bin/env node
/**
 * Regenerates the auto-generated block of CLAUDE_CONTEXT.md from the current
 * repository state (git history, feature layout, npm scripts, dependencies).
 *
 * Invoked by .husky/post-commit after every commit. Everything outside the
 * AUTO:BEGIN / AUTO:END markers is hand-written and never touched.
 *
 * Usage:
 *   node .hooks/update-context.js          regenerate in place
 *   node .hooks/update-context.js --check  exit 1 if the file is out of date
 */
'use strict';

const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const BEGIN = '<!-- AUTO:BEGIN - generated by .hooks/update-context.js, do not edit by hand -->';
const END = '<!-- AUTO:END -->';
const SEP = String.fromCharCode(31); // matches %x1f in the git pretty format below
const MAX_FILES = 20; // cap the last-commit file list so the block stays readable
const CHECK_ONLY = process.argv.includes('--check');

function git(args, fallback = '') {
  try {
    return execFileSync('git', args, { encoding: 'utf8' }).trim();
  } catch {
    return fallback;
  }
}

const repoRoot = git(['rev-parse', '--show-toplevel']) || process.cwd();
const targetFile = path.join(repoRoot, 'CLAUDE_CONTEXT.md');

function readJson(relPath) {
  try {
    return JSON.parse(fs.readFileSync(path.join(repoRoot, relPath), 'utf8'));
  } catch {
    return null;
  }
}

function listDirs(relPath) {
  try {
    return fs
      .readdirSync(path.join(repoRoot, relPath), { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .sort();
  } catch {
    return [];
  }
}

function countFiles(relPath, predicate) {
  let total = 0;
  const walk = (dir) => {
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (predicate(entry.name)) total += 1;
    }
  };
  walk(path.join(repoRoot, relPath));
  return total;
}

// ---------------------------------------------------------------- collectors

function collectGit() {
  const log = git(['log', '-12', '--pretty=format:%h%x1f%s%x1f%an%x1f%ad', '--date=short']);
  const commits = log
    ? log.split('\n').map((line) => {
        const [hash, subject, author, date] = line.split(SEP);
        return { hash, subject, author, date };
      })
    : [];
  return {
    branch: git(['rev-parse', '--abbrev-ref', 'HEAD'], 'unknown'),
    total: git(['rev-list', '--count', 'HEAD'], '0'),
    commits,
    // -m --first-parent so merge commits report a real file list instead of nothing.
    lastFiles: git([
      'diff-tree',
      '--no-commit-id',
      '--name-only',
      '-r',
      '-m',
      '--first-parent',
      'HEAD',
    ])
      .split('\n')
      .filter(Boolean),
    dirty: git(['status', '--porcelain']).split('\n').filter(Boolean).length,
  };
}

function collectFeatures() {
  return listDirs('src/app/features').map((name) => {
    const base = `src/app/features/${name}`;
    return {
      name,
      pages: listDirs(`${base}/pages`),
      components: listDirs(`${base}/components`),
      services: countFiles(`${base}/services`, (f) => f.endsWith('.ts') && !f.endsWith('.spec.ts')),
      specs: countFiles(base, (f) => f.endsWith('.spec.ts')),
    };
  });
}

function collectDocs() {
  const dir = 'docs/superpowers/specs';
  try {
    return fs
      .readdirSync(path.join(repoRoot, dir))
      .filter((f) => f.endsWith('.md'))
      .sort()
      .reverse()
      .map((f) => `${dir}/${f}`);
  } catch {
    return [];
  }
}

// ------------------------------------------------------------------ renderer

// Local YYYY-MM-DD: git log dates below are local too, so a UTC stamp here would
// read as a different day from the commits it summarises.
function localDate() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

function bullets(items, empty = '_(none)_') {
  return items.length ? items.map((line) => `- ${line}`).join('\n') : empty;
}

function render() {
  const pkg = readJson('package.json') || {};
  const gitInfo = collectGit();
  const features = collectFeatures();
  const docs = collectDocs();
  const deps = Object.entries(pkg.dependencies || {});
  const specCount = countFiles('src', (f) => f.endsWith('.spec.ts'));
  const head = gitInfo.commits[0];
  const now = localDate();

  const featureTable = features.length
    ? [
        '| Feature | Pages | Components | Services | Specs |',
        '| --- | --- | --- | --- | --- |',
        ...features.map(
          (f) =>
            `| \`${f.name}\` | ${f.pages.length ? f.pages.join(', ') : '-'} | ${f.components.length} | ${f.services} | ${f.specs} |`,
        ),
      ].join('\n')
    : '_No features found under `src/app/features`._';

  return [
    BEGIN,
    '',
    `_Last updated: ${now} - commit \`${head ? head.hash : 'n/a'}\` on \`${gitInfo.branch}\` - ${gitInfo.total} commits total._`,
    '',
    '### Runtime & tooling',
    '',
    bullets([
      `Package: \`${pkg.name || 'unknown'}\` v${pkg.version || '0.0.0'} (${pkg.packageManager || 'npm'})`,
      `Runtime deps: ${deps.length} - dev deps: ${Object.keys(pkg.devDependencies || {}).length}`,
      `Spec files under \`src/\`: ${specCount}`,
    ]),
    '',
    '### Runtime dependencies',
    '',
    bullets(deps.map(([name, range]) => `\`${name}\` ${range}`)),
    '',
    '### npm scripts',
    '',
    bullets(
      Object.entries(pkg.scripts || {}).map(([name, cmd]) => `\`npm run ${name}\` -> \`${cmd}\``),
    ),
    '',
    '### Feature modules',
    '',
    featureTable,
    '',
    '### Recent commits',
    '',
    bullets(gitInfo.commits.map((c) => `\`${c.hash}\` ${c.date} - ${c.subject} _(${c.author})_`)),
    '',
    '### Files touched by the last commit',
    '',
    bullets([
      ...gitInfo.lastFiles.slice(0, MAX_FILES).map((f) => `\`${f}\``),
      ...(gitInfo.lastFiles.length > MAX_FILES
        ? [`_...and ${gitInfo.lastFiles.length - MAX_FILES} more file(s)._`]
        : []),
    ]),
    '',
    '### Design specs',
    '',
    bullets(docs.map((d) => `[${path.basename(d)}](${d})`)),
    '',
    `_Working tree at generation time: ${gitInfo.dirty} uncommitted change(s)._`,
    '',
    END,
  ].join('\n');
}

// --------------------------------------------------------------------- main

function main() {
  if (!fs.existsSync(targetFile)) {
    console.error('[update-context] CLAUDE_CONTEXT.md not found - skipping.');
    return 0;
  }

  const current = fs.readFileSync(targetFile, 'utf8');
  const start = current.indexOf(BEGIN);
  const end = current.indexOf(END);
  if (start === -1 || end === -1 || end < start) {
    console.error('[update-context] AUTO:BEGIN/AUTO:END markers missing - skipping.');
    return 0;
  }

  const next = current.slice(0, start) + render() + current.slice(end + END.length);
  if (next === current) {
    console.log('[update-context] CLAUDE_CONTEXT.md already up to date.');
    return 0;
  }

  if (CHECK_ONLY) {
    console.error('[update-context] out of date. Run: node .hooks/update-context.js');
    return 1;
  }

  fs.writeFileSync(targetFile, next);
  console.log('[update-context] CLAUDE_CONTEXT.md updated (stage it with your next commit).');
  return 0;
}

try {
  process.exit(main());
} catch (error) {
  // Never break a commit because context generation failed.
  console.error('[update-context] failed:', error && error.message);
  process.exit(CHECK_ONLY ? 1 : 0);
}
