#!/usr/bin/env node
/**
 * Regenerates the auto-generated blocks of CLAUDE_CONTEXT.md (full project state)
 * and .claude-resume.md (short session-resume note) from the current repository
 * state (git history, feature layout, npm scripts, dependencies).
 *
 * Invoked by .husky/post-commit after every commit. Everything outside the
 * AUTO:BEGIN / AUTO:END markers in either file is hand-written and never touched.
 *
 * The hook folds the result back into the commit that produced it with
 * `git commit --amend`, so both generated blocks MUST be a fixed point of that
 * amend: nothing in them may depend on the commit's own hash, on whether
 * CLAUDE_CONTEXT.md/.claude-resume.md are part of the commit, or on the
 * working-tree state. Otherwise every commit ships a block describing a commit
 * that no longer exists. See the "Rendering rules" comments below before
 * adding a field.
 *
 * .claude-resume.md's "Next step" / "Blockers" fields read from commit-message
 * trailers (`Next:` / `Blocked-by:` or `Blockers:`) on HEAD when present, and
 * otherwise carry forward whatever was already in the file — the hook cannot
 * invent a plan or a blocker, so it never resets these fields to empty.
 *
 * Usage:
 *   node .hooks/update-context.js          regenerate in place
 *   node .hooks/update-context.js --check  exit 1 if either file is out of date
 */
'use strict';

const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const BEGIN = '<!-- AUTO:BEGIN - generated by .hooks/update-context.js, do not edit by hand -->';
const END = '<!-- AUTO:END -->';
const RESUME_BEGIN =
  '<!-- AUTO:BEGIN - generated by .hooks/update-context.js, do not edit by hand -->';
const RESUME_END = '<!-- AUTO:END -->';
const SEP = String.fromCharCode(31); // matches %x1f in the git pretty format below
const TRAILER_SEP = String.fromCharCode(30); // matches %x1e in the git pretty format below
const MAX_FILES = 20; // cap file lists so the blocks stay readable
const CHECK_ONLY = process.argv.includes('--check');

function git(args, fallback = '') {
  try {
    return execFileSync('git', args, { encoding: 'utf8' }).trim();
  } catch {
    return fallback;
  }
}

const repoRoot = git(['rev-parse', '--show-toplevel']) || process.cwd();
const contextFile = path.join(repoRoot, 'CLAUDE_CONTEXT.md');
const resumeFile = path.join(repoRoot, '.claude-resume.md');
// Both generated files are excluded from "files touched" lists: the amend adds
// them to the very commit being described, so listing them would make the
// block change on every regeneration and never settle.
const GENERATED_FILES = new Set(['CLAUDE_CONTEXT.md', '.claude-resume.md']);

function readJson(relPath) {
  try {
    return JSON.parse(fs.readFileSync(path.join(repoRoot, relPath), 'utf8'));
  } catch {
    return null;
  }
}

function listDirs(relPath) {
  try {
    return fs
      .readdirSync(path.join(repoRoot, relPath), { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .sort();
  } catch {
    return [];
  }
}

function countFiles(relPath, predicate) {
  let total = 0;
  const walk = (dir) => {
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (predicate(entry.name)) total += 1;
    }
  };
  walk(path.join(repoRoot, relPath));
  return total;
}

// ---------------------------------------------------------------- collectors

function collectGit() {
  const log = git(['log', '-12', '--pretty=format:%h%x1f%s%x1f%an%x1f%ad', '--date=short']);
  const commits = log
    ? log.split('\n').map((line) => {
        const [hash, subject, author, date] = line.split(SEP);
        return { hash, subject, author, date };
      })
    : [];
  return {
    branch: git(['rev-parse', '--abbrev-ref', 'HEAD'], 'unknown'),
    total: git(['rev-list', '--count', 'HEAD'], '0'),
    commits,
    // -m --first-parent so merge commits report a real file list instead of nothing.
    lastFiles: git([
      'diff-tree',
      '--no-commit-id',
      '--name-only',
      '-r',
      '-m',
      '--first-parent',
      'HEAD',
    ])
      .split('\n')
      .filter(Boolean)
      .filter((f) => !GENERATED_FILES.has(f)),
    // Body only (git's %b), i.e. everything after the subject line.
    headBody: git(['log', '-1', '--format=%b', 'HEAD']),
    // The *recognized* trailers (git's own algorithm: the contiguous run of
    // `key: value` lines - possibly separated by blank lines from separate -m
    // flags - at the very end of the message). Deliberately NOT a regex scan
    // over the whole body: a body paragraph that happens to start a wrapped
    // line with e.g. "Blockers:" as prose must not be mistaken for a trailer.
    headTrailers: git(['log', '-1', '--format=%(trailers:only,unfold,separator=%x1e)', 'HEAD'])
      .split(TRAILER_SEP)
      .map((s) => s.trim())
      .filter(Boolean),
  };
}

function collectFeatures() {
  return listDirs('src/app/features').map((name) => {
    const base = `src/app/features/${name}`;
    return {
      name,
      pages: listDirs(`${base}/pages`),
      components: listDirs(`${base}/components`),
      services: countFiles(`${base}/services`, (f) => f.endsWith('.ts') && !f.endsWith('.spec.ts')),
      specs: countFiles(base, (f) => f.endsWith('.spec.ts')),
    };
  });
}

function collectDocs() {
  const dir = 'docs/superpowers/specs';
  try {
    return fs
      .readdirSync(path.join(repoRoot, dir))
      .filter((f) => f.endsWith('.md'))
      .sort()
      .reverse()
      .map((f) => `${dir}/${f}`);
  } catch {
    return [];
  }
}

// ------------------------------------------------------------------ helpers

// Local YYYY-MM-DD: git log dates are local too, so a UTC stamp here would
// read as a different day from the commits it summarises.
function localDate() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

function bullets(items, empty = '_(none)_') {
  return items.length ? items.map((line) => `- ${line}`).join('\n') : empty;
}

// Last value wins, matching how git itself resolves a repeated trailer key.
// `trailers` must be lines git's own trailer parser recognized (see
// collectGit's headTrailers) - never a regex scan over the raw body, which
// would also match ordinary prose that happens to start a line with e.g.
// "Blockers:" as part of a sentence rather than an actual trailer.
function parseTrailer(trailers, keys) {
  const re = new RegExp(`^(?:${keys.join('|')})\\s*:\\s*(.+)$`, 'i');
  let value = null;
  for (const line of trailers) {
    const m = line.match(re);
    if (m) value = m[1].trim();
  }
  return value || null;
}

// Drops only the trailer lines git itself recognized off the tail of the raw
// body (plus the blank lines separating them), so a "## Next step / etc."
// mention inside an ordinary paragraph is left alone.
function stripTrailers(body, trailers) {
  const keys = new Set(
    trailers
      .map((line) => {
        const m = line.match(/^([A-Za-z][A-Za-z0-9-]*)\s*:/);
        return m ? m[1].toLowerCase() : null;
      })
      .filter(Boolean),
  );
  const lines = body.split('\n');
  let end = lines.length;
  while (end > 0 && lines[end - 1].trim() === '') end--;
  if (keys.size === 0) return lines.slice(0, end).join('\n').trim();

  let cut = end;
  while (cut > 0) {
    const line = lines[cut - 1];
    if (line.trim() === '') {
      cut--;
      continue;
    }
    const m = line.match(/^([A-Za-z][A-Za-z0-9-]*)\s*:/);
    if (m && keys.has(m[1].toLowerCase())) {
      cut--;
      continue;
    }
    break;
  }
  return lines.slice(0, cut).join('\n').trim();
}

// Pulls the text under a `## Heading` line (up to the next heading or the end
// of the string) out of a previously-generated block, so unset fields can
// carry their last known value forward instead of resetting to empty.
function extractSection(markdown, heading) {
  if (!markdown) return null;
  const lines = markdown.split('\n');
  const startIdx = lines.findIndex((line) => line.trim() === heading);
  if (startIdx === -1) return null;
  const rest = lines.slice(startIdx + 1);
  // Stop at the next heading OR at an AUTO:BEGIN/END marker. Without the
  // marker check, the last section in the block (Blockers) has nothing to
  // stop it, so it swallows the closing AUTO:END marker itself - which then
  // gets carried into the *next* render's Blockers value, appending a fresh
  // stray AUTO:END every single regeneration.
  const stopRe = /^#{1,6}\s|^<!--\s*AUTO:(BEGIN|END)/;
  const endIdx = rest.findIndex((line) => stopRe.test(line.trim()));
  const body = (endIdx === -1 ? rest : rest.slice(0, endIdx)).join('\n').trim();
  return body || null;
}

// ------------------------------------------------------------------ renderers

function renderContext(gitInfo) {
  const pkg = readJson('package.json') || {};
  const features = collectFeatures();
  const docs = collectDocs();
  const deps = Object.entries(pkg.dependencies || {});
  const specCount = countFiles('src', (f) => f.endsWith('.spec.ts'));
  const now = localDate();

  const featureTable = features.length
    ? [
        '| Feature | Pages | Components | Services | Specs |',
        '| --- | --- | --- | --- | --- |',
        ...features.map(
          (f) =>
            `| \`${f.name}\` | ${f.pages.length ? f.pages.join(', ') : '-'} | ${f.components.length} | ${f.services} | ${f.specs} |`,
        ),
      ].join('\n')
    : '_No features found under `src/app/features`._';

  return [
    BEGIN,
    '',
    // Rendering rule: no HEAD hash here. The amend rewrites it, so a hash
    // stamped now would name a commit that no longer exists a second later.
    `_Last updated: ${now} - branch \`${gitInfo.branch}\` - ${gitInfo.total} commits total._`,
    '',
    '### Runtime & tooling',
    '',
    bullets([
      `Package: \`${pkg.name || 'unknown'}\` v${pkg.version || '0.0.0'} (${pkg.packageManager || 'npm'})`,
      `Runtime deps: ${deps.length} - dev deps: ${Object.keys(pkg.devDependencies || {}).length}`,
      `Spec files under \`src/\`: ${specCount}`,
    ]),
    '',
    '### Runtime dependencies',
    '',
    bullets(deps.map(([name, range]) => `\`${name}\` ${range}`)),
    '',
    '### npm scripts',
    '',
    bullets(
      Object.entries(pkg.scripts || {}).map(([name, cmd]) => `\`npm run ${name}\` -> \`${cmd}\``),
    ),
    '',
    '### Feature modules',
    '',
    featureTable,
    '',
    '### Recent commits',
    '',
    // Rendering rule: HEAD is shown without its hash, for the same reason.
    bullets(
      gitInfo.commits.map((c, i) =>
        i === 0
          ? `**(this commit)** ${c.date} - ${c.subject} _(${c.author})_`
          : `\`${c.hash}\` ${c.date} - ${c.subject} _(${c.author})_`,
      ),
    ),
    '',
    '### Files touched by the last commit',
    '',
    bullets([
      ...gitInfo.lastFiles.slice(0, MAX_FILES).map((f) => `\`${f}\``),
      ...(gitInfo.lastFiles.length > MAX_FILES
        ? [`_...and ${gitInfo.lastFiles.length - MAX_FILES} more file(s)._`]
        : []),
    ]),
    '',
    '### Design specs',
    '',
    bullets(docs.map((d) => `[${path.basename(d)}](${d})`)),
    '',
    END,
  ].join('\n');
}

function renderResume(gitInfo, previousContent) {
  const now = localDate();
  const head = gitInfo.commits[0];
  const nextFromTrailer = parseTrailer(gitInfo.headTrailers, ['Next']);
  const blockedFromTrailer = parseTrailer(gitInfo.headTrailers, ['Blocked-by', 'Blockers']);
  const cleanedBody = stripTrailers(gitInfo.headBody, gitInfo.headTrailers);

  const nextStep =
    nextFromTrailer ||
    extractSection(previousContent, '## Next step') ||
    '_(none recorded — add a `Next:` trailer to a commit message to set this, ' +
      'e.g. `git commit -m "…" -m "Next: wire up X"`.)_';
  const blockers =
    blockedFromTrailer ||
    extractSection(previousContent, '## Blockers / notes') ||
    '_(none recorded — add a `Blocked-by:` trailer when something is blocking you.)_';

  return [
    RESUME_BEGIN,
    '',
    // Same fixed-point rule as CLAUDE_CONTEXT.md: no HEAD hash.
    `_Last updated: ${now} - branch \`${gitInfo.branch}\` - ${gitInfo.total} commits total._`,
    '',
    '## What happened last',
    '',
    head ? `**${head.subject}** _(${head.date}, ${head.author})_` : '_(no commits yet)_',
    ...(cleanedBody ? ['', cleanedBody] : []),
    '',
    '### Files touched',
    '',
    bullets([
      ...gitInfo.lastFiles.slice(0, MAX_FILES).map((f) => `\`${f}\``),
      ...(gitInfo.lastFiles.length > MAX_FILES
        ? [`_...and ${gitInfo.lastFiles.length - MAX_FILES} more file(s)._`]
        : []),
    ]),
    '',
    '## Next step',
    '',
    nextStep,
    '',
    '## Blockers / notes',
    '',
    blockers,
    '',
    RESUME_END,
  ].join('\n');
}

// --------------------------------------------------------------------- main

function planUpdate(targetPath, beginMarker, endMarker, renderFn) {
  const name = path.basename(targetPath);
  if (!fs.existsSync(targetPath)) {
    console.error(`[update-context] ${name} not found - skipping.`);
    return { name, status: 'missing' };
  }

  const current = fs.readFileSync(targetPath, 'utf8');
  const start = current.indexOf(beginMarker);
  const end = current.indexOf(endMarker);
  if (start === -1 || end === -1 || end < start) {
    console.error(`[update-context] AUTO:BEGIN/AUTO:END markers missing in ${name} - skipping.`);
    return { name, status: 'no-markers' };
  }

  const next = current.slice(0, start) + renderFn(current) + current.slice(end + endMarker.length);
  return { name, targetPath, status: next === current ? 'unchanged' : 'changed', next };
}

function main() {
  const gitInfo = collectGit();

  const plans = [
    planUpdate(contextFile, BEGIN, END, () => renderContext(gitInfo)),
    planUpdate(resumeFile, RESUME_BEGIN, RESUME_END, (prev) => renderResume(gitInfo, prev)),
  ];

  const changed = plans.filter((p) => p.status === 'changed');
  if (changed.length === 0) {
    console.log('[update-context] nothing to update.');
    return 0;
  }

  if (CHECK_ONLY) {
    for (const p of changed) console.error(`[update-context] ${p.name} is out of date.`);
    console.error('[update-context] run: node .hooks/update-context.js');
    return 1;
  }

  for (const p of changed) {
    fs.writeFileSync(p.targetPath, p.next);
    console.log(`[update-context] ${p.name} regenerated.`);
  }
  return 0;
}

try {
  process.exit(main());
} catch (error) {
  // Never break a commit because context generation failed.
  console.error('[update-context] failed:', error && error.message);
  process.exit(CHECK_ONLY ? 1 : 0);
}
